# 访问端口
server.port:
  8085

# 配置数据库
spring:
  datasource:
    #    url: jdbc:mysql://43.138.121.194:3306/online_edit?serverTimezone=Asia/Shanghai&allowMultiQueries=true&useAffectedRows=true
    url: jdbc:mysql://localhost:3306/elm?serverTimezone=Asia/Shanghai&allowMultiQueries=true&useAffectedRows=true
    username: root
    password: zzwzzw
    driver-class-name: com.mysql.cj.jdbc.Driver

# 配置 MyBatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.elm.pojo
  configuration:
    map-underscore-to-camel-case: true

# 对象存储
oss:
  qiniu:
    url: http://rvwv74zmk.hn-bkt.clouddn.com # 这里如果有自己的域名就去绑定自己的 没有的就只能使用七牛云的测试域名
    accessKey: vPExdWLiG0BUIn7IQppbJcIirPpbQbYSHBliIbT0
    secretKey: u9ioqCaoWFCIDIdlqLmNPFu5N6sBPvphETzKgnbW
    bucketName: caiwei-test

